//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaOffice.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisaOffice.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are Turkey&apos;s leading visa service provider, helping thousands of travelers obtain their visas quickly and efficiently..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Turkey Visa Office.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Services.
        /// </summary>
        public static string AllServices {
            get {
                return ResourceManager.GetString("AllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kızılay, Çankaya, Ankara 06420.
        /// </summary>
        public static string AnkaraOfficeAddress {
            get {
                return ResourceManager.GetString("AnkaraOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ankara@turkeyvisaoffice.com.
        /// </summary>
        public static string AnkaraOfficeEmail {
            get {
                return ResourceManager.GetString("AnkaraOfficeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday - Friday: 9:00 AM - 5:00 PM.
        /// </summary>
        public static string AnkaraOfficeHours {
            get {
                return ResourceManager.GetString("AnkaraOfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +90 312 456 7890.
        /// </summary>
        public static string AnkaraOfficePhone {
            get {
                return ResourceManager.GetString("AnkaraOfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications Processed.
        /// </summary>
        public static string ApplicationsProcessed {
            get {
                return ResourceManager.GetString("ApplicationsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for Turkey Visa.
        /// </summary>
        public static string ApplyForVisa {
            get {
                return ResourceManager.GetString("ApplyForVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        public static string ApplyNow {
            get {
                return ResourceManager.GetString("ApplyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Online.
        /// </summary>
        public static string ApplyOnline {
            get {
                return ResourceManager.GetString("ApplyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Appointment.
        /// </summary>
        public static string BookAppointment {
            get {
                return ResourceManager.GetString("BookAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Visa Office.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Business Visa.
        /// </summary>
        public static string BusinessVisa {
            get {
                return ResourceManager.GetString("BusinessVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For business meetings, conferences, trade shows, and commercial activities in Turkey..
        /// </summary>
        public static string BusinessVisaDesc {
            get {
                return ResourceManager.GetString("BusinessVisaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from our wide range of visa services.
        /// </summary>
        public static string ChooseFromWideRange {
            get {
                return ResourceManager.GetString("ChooseFromWideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Turkey visa services with expert guidance and fast processing. Your trusted partner for all Turkey visa and immigration needs..
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your visa application form below.
        /// </summary>
        public static string CompleteYourVisaApplication {
            get {
                return ResourceManager.GetString("CompleteYourVisaApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Support.
        /// </summary>
        public static string ComprehensiveSupport {
            get {
                return ResourceManager.GetString("ComprehensiveSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From application to approval, we support you every step of the way..
        /// </summary>
        public static string ComprehensiveSupportDesc {
            get {
                return ResourceManager.GetString("ComprehensiveSupportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Served.
        /// </summary>
        public static string CountriesServed {
            get {
                return ResourceManager.GetString("CountriesServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Translation.
        /// </summary>
        public static string DocumentTranslation {
            get {
                return ResourceManager.GetString("DocumentTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced Team.
        /// </summary>
        public static string ExperiencedTeam {
            get {
                return ResourceManager.GetString("ExperiencedTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team has extensive experience in Turkey visa regulations and immigration law..
        /// </summary>
        public static string ExperiencedTeamDesc {
            get {
                return ResourceManager.GetString("ExperiencedTeamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Guidance.
        /// </summary>
        public static string ExpertGuidance {
            get {
                return ResourceManager.GetString("ExpertGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional consultants with years of experience in Turkey visa regulations..
        /// </summary>
        public static string ExpertGuidanceDesc {
            get {
                return ResourceManager.GetString("ExpertGuidanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Family Reunification Visa.
        /// </summary>
        public static string FamilyVisa {
            get {
                return ResourceManager.GetString("FamilyVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For visiting family members or relatives residing in Turkey..
        /// </summary>
        public static string FamilyVisaDesc {
            get {
                return ResourceManager.GetString("FamilyVisaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Processing.
        /// </summary>
        public static string FastProcessing {
            get {
                return ResourceManager.GetString("FastProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick turnaround times with express processing options available for urgent applications..
        /// </summary>
        public static string FastProcessingDesc {
            get {
                return ResourceManager.GetString("FastProcessingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get expert guidance and fast processing for your visa needs..
        /// </summary>
        public static string GetExpertGuidance {
            get {
                return ResourceManager.GetString("GetExpertGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch with our expert team.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trusted partner for all Turkey visa and immigration needs. Fast, reliable, and professional service with expert guidance every step of the way..
        /// </summary>
        public static string HeroDescription {
            get {
                return ResourceManager.GetString("HeroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alsancak, Konak, İzmir 35220.
        /// </summary>
        public static string IzmirOfficeAddress {
            get {
                return ResourceManager.GetString("IzmirOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to izmir@turkeyvisaoffice.com.
        /// </summary>
        public static string IzmirOfficeEmail {
            get {
                return ResourceManager.GetString("IzmirOfficeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday - Friday: 9:00 AM - 5:00 PM.
        /// </summary>
        public static string IzmirOfficeHours {
            get {
                return ResourceManager.GetString("IzmirOfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +90 232 789 0123.
        /// </summary>
        public static string IzmirOfficePhone {
            get {
                return ResourceManager.GetString("IzmirOfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Advice.
        /// </summary>
        public static string LegalAdvice {
            get {
                return ResourceManager.GetString("LegalAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Consultation.
        /// </summary>
        public static string LegalConsultation {
            get {
                return ResourceManager.GetString("LegalConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksim Square, Beyoğlu, Istanbul 34437.
        /// </summary>
        public static string MainOfficeAddress {
            get {
                return ResourceManager.GetString("MainOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to istanbul@turkeyvisaoffice.com.
        /// </summary>
        public static string MainOfficeEmail {
            get {
                return ResourceManager.GetString("MainOfficeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday - Friday: 9:00 AM - 6:00 PM, Saturday: 10:00 AM - 2:00 PM.
        /// </summary>
        public static string MainOfficeHours {
            get {
                return ResourceManager.GetString("MainOfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +90 212 123 4567.
        /// </summary>
        public static string MainOfficePhone {
            get {
                return ResourceManager.GetString("MainOfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide reliable, fast, and professional visa services while ensuring complete customer satisfaction..
        /// </summary>
        public static string MissionDescription {
            get {
                return ResourceManager.GetString("MissionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        public static string Offices {
            get {
                return ResourceManager.GetString("Offices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string OurMission {
            get {
                return ResourceManager.GetString("OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalized Service.
        /// </summary>
        public static string PersonalizedService {
            get {
                return ResourceManager.GetString("PersonalizedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each application receives individual attention from our expert consultants..
        /// </summary>
        public static string PersonalizedServiceDesc {
            get {
                return ResourceManager.GetString("PersonalizedServiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Visa Types.
        /// </summary>
        public static string PopularVisaTypes {
            get {
                return ResourceManager.GetString("PopularVisaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Visa Services for Turkey.
        /// </summary>
        public static string ProfessionalVisaServices {
            get {
                return ResourceManager.GetString("ProfessionalVisaServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Turnaround.
        /// </summary>
        public static string QuickTurnaround {
            get {
                return ResourceManager.GetString("QuickTurnaround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We process applications efficiently to meet your travel deadlines..
        /// </summary>
        public static string QuickTurnaroundDesc {
            get {
                return ResourceManager.GetString("QuickTurnaroundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start your visa application?.
        /// </summary>
        public static string ReadyToStart {
            get {
                return ResourceManager.GetString("ReadyToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Process.
        /// </summary>
        public static string SecureProcess {
            get {
                return ResourceManager.GetString("SecureProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your documents and personal information are handled with the highest security standards..
        /// </summary>
        public static string SecureProcessDesc {
            get {
                return ResourceManager.GetString("SecureProcessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Student Visa.
        /// </summary>
        public static string StudentVisa {
            get {
                return ResourceManager.GetString("StudentVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For students enrolled in Turkish educational institutions for academic purposes..
        /// </summary>
        public static string StudentVisaDesc {
            get {
                return ResourceManager.GetString("StudentVisaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Rate.
        /// </summary>
        public static string SuccessRate {
            get {
                return ResourceManager.GetString("SuccessRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Available.
        /// </summary>
        public static string SupportAvailable {
            get {
                return ResourceManager.GetString("SupportAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Tourist Visa.
        /// </summary>
        public static string TouristVisa {
            get {
                return ResourceManager.GetString("TouristVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect for leisure travel, sightseeing, and exploring Turkey&apos;s rich culture and history..
        /// </summary>
        public static string TouristVisaDesc {
            get {
                return ResourceManager.GetString("TouristVisaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Application.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Application.
        /// </summary>
        public static string TrackApplication {
            get {
                return ResourceManager.GetString("TrackApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Transit Visa.
        /// </summary>
        public static string TransitVisa {
            get {
                return ResourceManager.GetString("TransitVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For travelers passing through Turkey to reach their final destination..
        /// </summary>
        public static string TransitVisaDesc {
            get {
                return ResourceManager.GetString("TransitVisaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Visa Types.
        /// </summary>
        public static string ViewAllVisaTypes {
            get {
                return ResourceManager.GetString("ViewAllVisaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Application Form.
        /// </summary>
        public static string VisaApplicationForm {
            get {
                return ResourceManager.GetString("VisaApplicationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Services.
        /// </summary>
        public static string VisaServices {
            get {
                return ResourceManager.GetString("VisaServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Type Required.
        /// </summary>
        public static string VisaTypeRequired {
            get {
                return ResourceManager.GetString("VisaTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Types.
        /// </summary>
        public static string VisaTypes {
            get {
                return ResourceManager.GetString("VisaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose Us.
        /// </summary>
        public static string WhyChooseUs {
            get {
                return ResourceManager.GetString("WhyChooseUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey Work Visa.
        /// </summary>
        public static string WorkVisa {
            get {
                return ResourceManager.GetString("WorkVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For individuals seeking employment or already employed in Turkey..
        /// </summary>
        public static string WorkVisaDesc {
            get {
                return ResourceManager.GetString("WorkVisaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Subject.
        /// </summary>
        public static string YourSubject {
            get {
                return ResourceManager.GetString("YourSubject", resourceCulture);
            }
        }
    }
}
